BASE_PATH_THICKNESS = 5
MAX_PATH_THICKNESS = 40

CANVAS_SIDE_LEN = 600

INPUT_MIN = {-2, -2}
INPUT_MAX = {3, 3}
OUTPUT_MIN = {-2, -2}
OUTPUT_MAX = {3, 3}

INPUT_AREA = (INPUT_MAX[1] - INPUT_MIN[1]) * (INPUT_MAX[2] - INPUT_MIN[2])
OUTPUT_AREA = (OUTPUT_MAX[1] - OUTPUT_MIN[1]) * (OUTPUT_MAX[2] - OUTPUT_MIN[2])

MAX_PIXEL_DISTANCE_BEFORE_INTERP = 50
MAX_PIXEL_DISTANCE_BEFORE_DISCONTINUITY = 250
INTERP_STEPS = 20
MAX_INTERP_TRIES = 2
MIN_PIXEL_DIST_FOR_NEW_POINT = 5

DEFAULT_FUNC = "z * z"
